### PR TITLE
Copy inviter ID on click

### PR DESCRIPTION
**Pull request by FrostBird347**
This makes it far easier to report the account that created an invite being used by bot accounts.

### CODE REVIEW

**Review by HypedDomi — CHANGES_REQUESTED** [review]
Looks good, but you can't copy the ID with it, you have to type it yourself. Could you turn the ID into a react element that copies the ID when you click

**Comment by HypedDomi** [comment]
If you can't, that's no problem. Then I do that after the merge

**Comment by FrostBird347** [comment]
I first attempted to make it copy the ID when you click on the picture using `navigator.clipboard.writeText`, however it failed with `DOMException: Write permission denied.`
Another method that I hadn't attempted was creating an element, selecting that, copying the text and removing the element.

**Comment by FrostBird347** [comment]
It was far easier and less complicated to implement the latter method than I had feared.
The ID is no longer displayed and instead copied with a notification (BdApi.showToast).

**Comment by HypedDomi** [comment]
`Library.DiscordModules.ElectronModule.copy()` should work too. But looks fine right now

**Comment by FrostBird347** [comment]
Changed it to `Library.DiscordModules.ElectronModule.copy()`, as selected text isn't preserved when the previous method is used.

**Comment by HypedDomi** [comment]
Thank you ^^

**Pull request merged**
